name: PHP Code Check
on: [push]

jobs:
  check-php-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for PHP tags and TODO comments
        run: |
          if (git grep -l -e "<?php" -- "*.php" | xargs grep -l "TODO"); then
            echo "ERROR: PHP tags or TODO comments found in the code."
            exit 1
          fi
